### ISSUE TITLE
Crash with GPU OC higher than 1075Mhz

### ISSUE THREAD

**Issue by NaGaa95** [KazushiMe/Switch-OC-Suite#22]
Anything higher than 1075Mhz on the GPU will cause a game crash / application error 

I try with 2 Different switch OLED and it happen at the exact same clock speed so maybe a higher voltage is needed ?

For ram OC :
On both switch OLED with Samsung LPDDR4X, 2131MHz (mtcConf set to 1) is 100% stable without overvolt, a more agressive timing profil could be introduce for better performance ?

Thanks

**Comment by KazushiMe** [comment]
> Anything higher than 1075Mhz on the GPU will cause a game crash / application error

Needs detailed info (log reports for the game crash and sys-clk, power supply and frequencies).

> a more agressive timing profil could be introduce for better performance

You could calculate some of mtc parameters yourself and apply them to loader.kip. But I have no intention to explore further as it is very time-consuming.

**Comment by ms2048** [comment]
This is really depending on individual unit's characteristics, I suppose sort of a 'chip lottery'. For example, my OLED unit could be overclocked to 2397/1305 CPU/GPU for a first month - but then something happened (?) and now it only accepts 2193 or below for a CPU (regardless of GPU oc) and otherwise hangs or crashes. Still, the GPU can be set to whatever freq with no problems.

All this seems like a completely different set of constraints.

However, this unit has Micron RAM which can only be oc up to 1862, also I am using an old version of the software, as it does not throttle the handheld mode. I'm not sure how exactly these differences could affect things.

**Comment by NaGaa95** [comment]
> Needs detailed info (log reports for the game crash and sys-clk, power supply and frequencies).
Log report : https://pastebin.com/JeCpCwuZ

Docked Mode with original adapter 39w
CPU : 2091Mhz (100% Stable even at 2390Mhz)
GPU : 1152Mhz 
Ram : 2131Mhz

Tested on Dark Souls with 60FPS Patch to put maximum load on the system
The game always crash after 10 - 15 sec most of the time with application error and some time need to force shutdown the switch

I also try with 4IFIR it's stable at max clock but don't see any performance improvement after 1075Mhz  

> This is really depending on individual unit's characteristics, I suppose sort of a 'chip lottery'. For example, my OLED unit could be overclocked to 2397/1305 CPU/GPU for a first month - but then something happened (?) and now it only accepts 2193 or below for a CPU (regardless of GPU oc) and otherwise hangs or crashes. Still, the GPU can be set to whatever freq with no problems.

Yes that's whats i think at first but since i try it with 2 different OLED and it crash at the exact same clock speed maybe it can be fixed
